config/routes.rb
Rails.application.routes.draw do
  root 'leagues#index'

  get '/secret' => 'team_admin/registrations#new'

  devise_for :league_admins, controllers: { sessions: 'league_admin/sessions', registrations: 'league_admin/registrations' }, :skip => [ :sessions, :passwords ]

  devise_for :team_admins, :skip => [ :sessions, :passwords ], controllers: { sessions: 'team_admin/sessions', registrations: 'team_admin/registrations' }

  patch "team_admins/:id/edit" => "leagues#activate", :as => "approve_team_manager"

  delete "team_admins/:id" => "leagues#deactivate", :as => "disapprove_team_manager"

  devise_scope :league_admin do
    get '/sign_in'    => 'league_admin/sessions#new', :as => :new_league_admin_session
    match '/sign_in'  => 'league_admin/sessions#new', :as => :new_session, via: 'get'
    post 'sign_in'    => 'league_admin/sessions#create', :as => :create_session
    delete 'sign_out' => 'league_admin/sessions#destroy', :as => :destroy_session
    match 'sign_out'  => 'league_admin/sessions#destroy', :as => :destroy_league_admin_session, via: 'delete'
    match 'sign_out'  => 'league_admin/sessions#destroy', :as => :destroy_admin_league_admin_session, via: 'delete'
  end

  namespace :team_admin do
    get '/' => redirect('/team_admin'), as: 'root'
  end

  devise_for :team_admins, :skip => [ :registrations, :passwords ], controllers: { sessions: 'team_admin/sessions', registrations: 'team_admin/registrations' }
  resources :trades, :except => [ :delete ] do
    patch :accept
  end
  resources :posts, :except => [ :index ]
  resources :games
  resources :players
  resources :teams
  resources :trade_players

end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :teams
  belongs_to :league_admin
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
    @posts = Post.last(6)
    @games = (Game.where("date_time >= ?", Date.today).order("date_time ASC").first(13)).select do |game|
    @teams_need_admin = Team.where(team_admin_id: nil)
      if game.home_team_score.nil?
        game
      end
    end
    if params[:approved] == "false"
      @teamadmins = TeamAdmin.find_by_approved(false)
    else
      @teamadmins = TeamAdmin.all
    end
  end

  def activate
    teamadmin = TeamAdmin.find(params[:id])
    teamadmin.update_attribute(:approved, true)
    Team.find(params[:team]).update(team_admin_id: teamadmin.id)
    redirect_to "/"
  end

  def deactivate
    teamadmin = TeamAdmin.find(params[:id])
    teamadmin.destroy!
    redirect_to "/"
  end
  # GET /leagues/1
  # GET /leagues/1.json
  # def show
  # end

  # GET /leagues/new
  # def new
  #   @league = League.new
  # end

  # GET /leagues/1/edit
  # def edit
  # end

  # POST /leagues
  # POST /leagues.json
  # def create
  #   @league = League.new(league_params)

  #   respond_to do |format|
  #     if @league.save
  #       format.html { redirect_to @league, notice: 'League was successfully created.' }
  #       format.json { render :show, status: :created, location: @league }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @league.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  # def update
  #   respond_to do |format|
  #     if @league.update(league_params)
  #       format.html { redirect_to @league, notice: 'League was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @league }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @league.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  # def destroy
  #   @league.destroy
  #   respond_to do |format|
  #     format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # private
    # Use callbacks to share common setup or constraints between actions.
    # def set_league
    #   @league = League.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def league_params
    #   params.require(:league).permit(:league_admin_id, :name, :sport)
    # end
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_admin_id %><br>
    <%= f.number_field :league_admin_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>
<section style="text-align:center;">
  <%= render 'form' %>

  <button><%= link_to 'Show', @league %></button> |
  <button><%= link_to 'Back', leagues_path %></button>
</section>

app/views/leagues/index.html.erb
<% if league_admin_signed_in?  %>
  <nav>
    <strong><u>League Admin Options:</u></strong><br>
    <button><%= link_to 'Add Team', new_team_path %></button>
    <button><%= link_to 'Add Game', new_game_path %></button>
    <button><%= link_to 'Edit Game', games_path %></button>
  </nav><br>

  <% if @teamadmins.map{|admin| admin.approved}.any? %>
    <strong><u>Team managers awaiting approval:</u></strong>
  <% end %>

  <% @teamadmins.each do |teamadmin| %>
    <% if !teamadmin.approved %>
      <br><span><strong>Email: </strong><%= teamadmin.email %><br>  <strong>Name: </strong><%= teamadmin.full_name %></span><br>
      <% if @teams_need_admin.any? %>
        <form action="<%= approve_team_manager_path(teamadmin) %>" method="post" style="float:left;">
          <input type="hidden" name="_method" value="patch" />
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <% @teams_need_admin.each do |team| %>
            <%= team.name %>
            <input type="radio" name="team" value="<%= team.id %>">
          <% end %>
          <button type="submit" value="Approve">Approve</button>
        </form>
      <% end %>
      <button><%= link_to 'Deny', disapprove_team_manager_path(teamadmin), method: :delete %></button><br><br>
    <% end %>
  <% end %>
<% end %>

<h1>Upcoming Games</h1>

  <section id="second_section">
    <div class='blog'>
      <%= render partial: 'games/schedule' %>
    </div>
  </section>

<h1>News Posts</h1>
  <section id="third_section">
    <div>
      <%= render partial: 'posts/recent' %>
    </div>
</section>

app/views/leagues/new.html.erb
<h1>New League</h1>

<section style="text-align:center;">
  <%= render 'form' %>

  <button><%= link_to 'Back', leagues_path %></button>
</section>

app/views/leagues/show.html.erb
<section id="first_section">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>League admin:</strong>
    <%= @league.league_admin_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @league.name %>
  </p>

  <p>
    <strong>Sport:</strong>
    <%= @league.sport %>
  </p>

  <button><%= link_to 'Edit', edit_league_path(@league) %></button> |
  <button><%= link_to 'Back', leagues_path %></button>
</section>