config/routes.rb
Rails.application.routes.draw do
  root 'leagues#index'

  get '/secret' => 'team_admin/registrations#new'

  devise_for :league_admins, controllers: { sessions: 'league_admin/sessions', registrations: 'league_admin/registrations' }, :skip => [ :sessions, :passwords ]

  devise_for :team_admins, :skip => [ :sessions, :passwords ], controllers: { sessions: 'team_admin/sessions', registrations: 'team_admin/registrations' }

  patch "team_admins/:id/edit" => "leagues#activate", :as => "approve_team_manager"

  delete "team_admins/:id" => "leagues#deactivate", :as => "disapprove_team_manager"

  devise_scope :league_admin do
    get '/sign_in'    => 'league_admin/sessions#new', :as => :new_league_admin_session
    match '/sign_in'  => 'league_admin/sessions#new', :as => :new_session, via: 'get'
    post 'sign_in'    => 'league_admin/sessions#create', :as => :create_session
    delete 'sign_out' => 'league_admin/sessions#destroy', :as => :destroy_session
    match 'sign_out'  => 'league_admin/sessions#destroy', :as => :destroy_league_admin_session, via: 'delete'
    match 'sign_out'  => 'league_admin/sessions#destroy', :as => :destroy_admin_league_admin_session, via: 'delete'
  end

  namespace :team_admin do
    get '/' => redirect('/team_admin'), as: 'root'
  end

  devise_for :team_admins, :skip => [ :registrations, :passwords ], controllers: { sessions: 'team_admin/sessions', registrations: 'team_admin/registrations' }
  resources :trades, :except => [ :delete ] do
    patch :accept
  end
  resources :posts, :except => [ :index ]
  resources :games
  resources :players
  resources :teams
  resources :trade_players

end

app/models/trade.rb
class Trade < ActiveRecord::Base
  has_many   :trade_players
  has_many   :current_teams, class_name: :TradePlayer
  belongs_to :proposing_team, foreign_key: :proposing_team_id, class_name: :Team
  belongs_to :accepting_team, foreign_key: :accepting_team_id, class_name: :Team

  has_many :accepting_team_players, ->(accepting_team) { where current_team: accepting_team }, class_name: :TradePlayer
  has_many :proposing_team_players, ->(proposing_team) { where current_team: proposing_team }, class_name: :TradePlayer

  def readable_date
    self.created_at.strftime("%B %d, %Y")
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_team_admin!, except: [:index]

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.where(accepted: true)
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @tradeplayer = TradePlayer.new
    @trade = Trade.find(params[:id])
  end

  # GET /trades/new
  def new
    @trade = Trade.new
    @team = Team.new
  end

  # GET /trades/1/edit
  def edit
    @proposing_team = @trade.proposing_team
    @accepting_team = @trade.accepting_team
  end

  # POST /trades
  # POST /trades.json
  def create
    puts "#{params}"
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

      # @trade.trade_players.build(player: players.first, current_team: @trade.proposing_team)
      # @trade.trade_players.build(player: players.first, current_team: @trade.accepting_team)

  def accept
    @trade = Trade.find(params[:trade_id])
    proposing_team = @trade.proposing_team
    accepting_team = @trade.accepting_team

    proposed = team_players(@trade.trade_players, proposing_team).map{|trade| trade.player }
    acceptor = team_players(@trade.trade_players, accepting_team).map{|trade| trade.player }

    proposed = proposed.each{|player| Player.find(player.team_id).update(team_id: accepting_team.id)}
    acceptor = acceptor.each{|player| Player.find(player.team_id).update(team_id: proposing_team.id)}

    # proposedtraded = (proposing_team.players - proposed) + acceptor
    # acceptedtraded = (accepting_team.players - acceptor) + proposed

    # Team.find(proposing_team.id).players = proposedtraded
    # Team.find(accepting_team.id).players = acceptedtraded

    redirect_to '/'
  end
  # PATCH/PUT /trades/1

  def update
    respond_to do |format|
      update_trade_proposing_team(proposing_team_params,@trade)
      update_trade_accepting_team(accepting_team_params,@trade)
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url, notice: 'Trade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    def team_players(trade_players, team)
      trade_players.select do |trade_player|
        if trade_player.player.team == team
          trade_player.player
        end
      end
    end

    def update_team_players(players, new_team)
      players.each do |player|
        player.player.update(team_id: new_team.id)
      end
    end

    def update_trade_proposing_team (params, trade)
      params.each do |param|
        trade.proposing_team_players.build(player: Player.find(param.to_i) )
      end
    end

    def update_trade_accepting_team (params, trade)
      params.each do |param|
        trade.accepting_team_players.build(player: Player.find(param.to_i) )
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:proposing_team_id, :accepting_team_id, :accepted)
    end

    def proposing_team_params
      proposing_team = params.require(:proposing_team)
      proposing_team_players = proposing_team[:player_id].delete_if{|x| x == ""}
    end

    def accepting_team_params
      accepting_team = params.require(:accepting_team)
      accepting_team_players = accepting_team[:player_id].delete_if{|x| x == ""}
    end

end

app/views/trades/_2proposed.html.slim
=@team.name

-@proposedtrades.each do |trade|
  =trade.id
  end

app/views/trades/_details.html.erb
<section id="first_section">

  <h3> Proposing Team: <%=@proposing_team.teamcity  %> </h3>

  <%@trade.trade_players.each do |trade_player|  %>
    <%if trade_player.player.team == @proposing_team%>
      <div>
        <%= trade_player.player.full_name %>
      </div>
    <% end %>
  <% end %>


  <h3> Reviewing Team: <%=@accepting_team.teamcity  %> </h3>

  <%@trade.trade_players.each do |trade_player|  %>
    <%if trade_player.player.team == @accepting_team%>
      <div>
        <%= trade_player.player.full_name %>

      </div>
    <% end %>
  <% end %>
</section>

app/views/trades/_details.html.slim
h3 Proposing Team:
=@trade.proposing_team.name
p players
  @trade.proposing_team.players.each do |player|
    =player.first_name
  end

app/views/trades/_extra_form.html.slim
= simple_form_for @trade do |form|
  strong Proposing Team
  = simple_fields_for :proposing_team, @trade.trade_players.build do |fields|
    = fields.association :player, collection: @trade.proposing_team.players, as: :check_boxes, label_method: :first_name, value_method: :id
  strong Accepting Team
  = simple_fields_for :accepting_team, @trade.trade_players.build do |fields|
    = fields.association :player, collection: @trade.accepting_team.players, as: :check_boxes, label_method: :first_name, value_method: :id
  = form.submit :'Add Players'

app/views/trades/_form.html.erb
<%= simple_form_for @trade, input_html: { class: 'new_trade' }   do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>
      <ul>
      <% @trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :proposing_team, input_html: {class: 'proposing_team_trade'} %>
  <%= f.association :accepting_team, input_html: {class: 'accepting_team_trade'}%>
  <%= f.submit %>

<% end %>

app/views/trades/_proposed.html.erb
<h4> Trades Proposed </h3>
<table>
  <thead>
    <tr>
      <td><b> Team </b> </td>
      <td><b> Date Requested</b> </td>
      <td> </td>
    </tr>
  </thead>
  <% @proposedtrades.each do |trade| %>
    <tr>
      <td> <%=trade.accepting_team.name %> </td>
      <td> <%=trade.created_at.strftime('%m/%d/%y') %></td>
      <td> <%=link_to 'Review Trade', edit_trade_path(trade) %> </td>
      <% end %>
    </tr>
</table>

app/views/trades/_review.html.erb
<h4> Trades to Review </h4>
<table>
  <thead>
    <tr>
      <td><b> Team </b> </td>
      <td><b> Date Requested</b> </td>
      <td> </td>
    </tr>
  </thead>
  <% @reviewabletrades.each do |trade| %>
    <tr>
      <td> <%=trade.proposing_team.name %> </td>
      <td> <%=trade.created_at.strftime('%m/%d/%y') %></td>
      <td> <%=link_to 'Review Trade', edit_trade_path(trade) %> </td>
      <% end %>
    </tr>
</table>

app/views/trades/edit.html.erb
.<p id="notice"><%= notice %></p>
<h1>Accept or Decline Trade</h1>

<section style="text-align:center;">
  <%= render 'details' %>

  <br>
  <% if team_admin_signed_in?  %>
    <% if current_team_admin.id == @accepting_team.team_admin_id %>
      <button><%= link_to 'Accept', trade_accept_path(@trade), method: :patch %></button>
      <button><%= link_to 'Decline', trade_path(@trade)%></button>
    <% end %>
  <% end %>
</section>

app/views/trades/index.html.erb
<h1>All Trades</h1>

<section id="first_section">
<% if team_admin_signed_in? %>
  <button id="float-right"><a href="/trades/new">Create New Trade</a></button>
<% end %>
      <% @trades.each do |trade| %>
        <div>Trade made on <%= trade.updated_at.strftime('%m/%d/%y') %></div>
        <strong><%= trade.proposing_team.name %>: </strong>
          <%trade.trade_players.each do |trade_player|  %>
             <%if trade_player.player.team == trade.proposing_team%>
                <%= trade_player.player.full_name %>,
            <% end %>
          <% end %><br>
        <strong><%= trade.accepting_team.name %>: </strong>
         <%trade.trade_players.each do |trade_player|  %>
             <%if trade_player.player.team == trade.accepting_team%>
                <%= trade_player.player.full_name %>,
            <% end %>
          <% end %>
      <% end %>
      <div class="linebreak"></div>
</section>

app/views/trades/new.html.erb
<h1>New Trade</h1>
<section style="text-align:center;">
  <%= render 'form' %>

  <div proposing_team_id>
  </div>

  <div>
  </div>
  <button><%= link_to 'Back', trades_path %></button>
</section>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<section>
  <h1>Add players to trade</h1>
  <p>
    <%= render 'extra_form' %>
  </p>
</section>