config/routes.rb
Rails.application.routes.draw do
  root 'leagues#index'

  get '/secret' => 'team_admin/registrations#new'

  devise_for :league_admins, controllers: { sessions: 'league_admin/sessions', registrations: 'league_admin/registrations' }, :skip => [ :sessions, :passwords ]

  devise_for :team_admins, :skip => [ :sessions, :passwords ], controllers: { sessions: 'team_admin/sessions', registrations: 'team_admin/registrations' }

  patch "team_admins/:id/edit" => "leagues#activate", :as => "approve_team_manager"

  delete "team_admins/:id" => "leagues#deactivate", :as => "disapprove_team_manager"

  devise_scope :league_admin do
    get '/sign_in'    => 'league_admin/sessions#new', :as => :new_league_admin_session
    match '/sign_in'  => 'league_admin/sessions#new', :as => :new_session, via: 'get'
    post 'sign_in'    => 'league_admin/sessions#create', :as => :create_session
    delete 'sign_out' => 'league_admin/sessions#destroy', :as => :destroy_session
    match 'sign_out'  => 'league_admin/sessions#destroy', :as => :destroy_league_admin_session, via: 'delete'
    match 'sign_out'  => 'league_admin/sessions#destroy', :as => :destroy_admin_league_admin_session, via: 'delete'
  end

  namespace :team_admin do
    get '/' => redirect('/team_admin'), as: 'root'
  end

  devise_for :team_admins, :skip => [ :registrations, :passwords ], controllers: { sessions: 'team_admin/sessions', registrations: 'team_admin/registrations' }
  resources :trades, :except => [ :delete ] do
    patch :accept
  end
  resources :posts, :except => [ :index ]
  resources :games
  resources :players
  resources :teams
  resources :trade_players

end

app/views/layouts/_header.html.slim
section.header
  = link_to image_tag("05_NHL_Shield.svg.png", alt: :logo), root_path
  - if @team.present? && @team.persisted?
    h1 = link_to @team.name, team_path(@team)
  - else
    h1 = link_to 'NHL', root_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NHL</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Abel|Oxygen|Roboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body id="bootstrap-overrides">

  <div id='containinside'>
  <%= render 'layouts/header' %>

  <nav class="navbar navbar-inverse" style="width:100%;">
    <div class="container-fluid">
      <div class="navbar-header">
        <% if league_admin_signed_in? %>
          <a class="navbar-brand" href="/">Welcome, <%= current_league_admin.full_name %>. League Administrator.</a>
        <% elsif team_admin_signed_in? %>
          <% team = Team.where(id: current_team_admin.id) %>
          <a class="navbar-brand" href="/teams/<%= team[0].id %>">Welcome, <%= current_team_admin.full_name %>. <%= Team.find_by(team_admin_id: current_team_admin.id).name %> Manager</a>
        <% end %>
      </div>
      <ul class="nav navbar-nav" style="float:right;">
        <li><a href="/">Home</a></li>
        <li><a href="/teams">Teams</a></li>
        <li><a href="/games">Schedule</a></li>
        <li><a href="/players">Roster</a></li>
        <li><a href="/trades">Trades</a></li>
        <% if league_admin_signed_in? || team_admin_signed_in? %>
          <li><%= link_to('Logout', destroy_league_admin_session_path, :method => :delete) %></li>
        <% else %>
          <li><%= link_to('Register', new_league_admin_registration_path) %></li>
          <li><%= link_to('Login', new_league_admin_session_path ) %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <%= yield %>
  </div>
</body>

</html>

app/views/layouts/twodiv_template.html.erb
<h1>Schedule</h1>
<section id="first_section">
</section>
<h1>News/Trades</h1>
<section id="second_section">
</section>